// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEK40jqXCaUCs-jSJI6DViVFdiU_SWaM8',
    appId: '1:981168352717:web:b9ab0e31a3e0f5d8992884',
    messagingSenderId: '981168352717',
    projectId: 'cookwithme-4dc5c',
    authDomain: 'cookwithme-4dc5c.firebaseapp.com',
    databaseURL: 'https://cookwithme-4dc5c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookwithme-4dc5c.appspot.com',
    measurementId: 'G-J1YWBC7HX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMAnroUE7keR7zLXuSu3RkIbnw_prFnuw',
    appId: '1:981168352717:android:829d91d4a338101b992884',
    messagingSenderId: '981168352717',
    projectId: 'cookwithme-4dc5c',
    databaseURL: 'https://cookwithme-4dc5c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookwithme-4dc5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkSoCyqQ5KUWSDikvzuZ8U9hAZ_WXJ4vI',
    appId: '1:981168352717:ios:9f7c1405637d3539992884',
    messagingSenderId: '981168352717',
    projectId: 'cookwithme-4dc5c',
    databaseURL: 'https://cookwithme-4dc5c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookwithme-4dc5c.appspot.com',
    iosBundleId: 'com.example.cookWithMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkSoCyqQ5KUWSDikvzuZ8U9hAZ_WXJ4vI',
    appId: '1:981168352717:ios:9f7c1405637d3539992884',
    messagingSenderId: '981168352717',
    projectId: 'cookwithme-4dc5c',
    databaseURL: 'https://cookwithme-4dc5c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookwithme-4dc5c.appspot.com',
    iosBundleId: 'com.example.cookWithMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEK40jqXCaUCs-jSJI6DViVFdiU_SWaM8',
    appId: '1:981168352717:web:61c6ae6b2780ebb8992884',
    messagingSenderId: '981168352717',
    projectId: 'cookwithme-4dc5c',
    authDomain: 'cookwithme-4dc5c.firebaseapp.com',
    databaseURL: 'https://cookwithme-4dc5c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookwithme-4dc5c.appspot.com',
    measurementId: 'G-YF5J8MYKK4',
  );
}
